import type { RouteObject } from "react-router-dom";
import {
  DashboardPage,
  ProfilePage,
  StudentsPage,
  StudentDetailPage,
  ProgramsPage,
  CoursesPage,
  AnalyticsPage,
  GovernancePage,
  SettingsPage,
  UserManagementPage,
  MFASetupPage,
  DataSourcesPage,
  DataMappingPage,
  DataQualityPage,
  PipelineVisualizerPage,
  AccreditationPage,
  DataGovernancePage,
  SecurityAccessPage,
  StudentSuccessPredictionPage,
  NotificationsPage,
  SupportPage,
  LoginPage,
} from "../components/pages";

export const appRoutes: RouteObject[] = [
  { path: "/login", element: <LoginPage /> },
  { path: "/", element: <DashboardPage /> },
  { path: "/dashboard", element: <DashboardPage /> },
  { path: "/notifications", element: <NotificationsPage /> },
  { path: "/support", element: <SupportPage /> },
  { path: "/profile", element: <ProfilePage /> },
  { path: "/students", element: <StudentsPage /> },
  { path: "/students/:id", element: <StudentDetailPage /> },
  { path: "/programs", element: <ProgramsPage /> },
  { path: "/courses", element: <CoursesPage /> },
  { path: "/analytics", element: <AnalyticsPage /> },
  { path: "/governance", element: <GovernancePage /> },
  { path: "/settings", element: <SettingsPage /> },
  { path: "/users", element: <UserManagementPage /> },
  { path: "/security", element: <MFASetupPage /> },
  { path: "/data-sources", element: <DataSourcesPage /> },
  { path: "/data-mapping", element: <DataMappingPage /> },
  { path: "/data-quality", element: <DataQualityPage /> },
  { path: "/pipeline", element: <PipelineVisualizerPage /> },
  { path: "/accreditation", element: <AccreditationPage /> },
  { path: "/data-governance", element: <DataGovernancePage /> },
  { path: "/security-access", element: <SecurityAccessPage /> },
  { path: "/success-prediction", element: <StudentSuccessPredictionPage /> },
];
