import type { RouteObject } from "react-router-dom";
import {
  DashboardPage,
  ProfilePage,
  StudentsPage,
  ProgramsPage,
  CoursesPage,
  AnalyticsPage,
  ReportsPage,
  GovernancePage,
  SettingsPage,
  UserManagementPage,
  MFASetupPage,
  DataSourcesPage,
  DataMappingPage,
  DataQualityPage,
  PipelineVisualizerPage,
} from "../components/pages";

export const appRoutes: RouteObject[] = [
  { path: "/", element: <DashboardPage /> },
  { path: "/dashboard", element: <DashboardPage /> },
  { path: "/profile", element: <ProfilePage /> },
  { path: "/students", element: <StudentsPage /> },
  { path: "/programs", element: <ProgramsPage /> },
  { path: "/courses", element: <CoursesPage /> },
  { path: "/analytics", element: <AnalyticsPage /> },
  { path: "/reports", element: <ReportsPage /> },
  { path: "/governance", element: <GovernancePage /> },
  { path: "/settings", element: <SettingsPage /> },
  { path: "/users", element: <UserManagementPage /> },
  { path: "/security", element: <MFASetupPage /> },
  { path: "/data-sources", element: <DataSourcesPage /> },
  { path: "/data-mapping", element: <DataMappingPage /> },
  { path: "/data-quality", element: <DataQualityPage /> },
  { path: "/pipeline", element: <PipelineVisualizerPage /> },
];
