export { default as LoginPage } from "./LoginPage";
export { default as DashboardPage } from "./DashboardPage";
export { default as StudentsPage } from "./StudentsPage";
export { default as ProgramsPage } from "./ProgramsPage";
export { default as CoursesPage } from "./CoursesPage";
export { default as AnalyticsPage } from "./AnalyticsPage";
export { default as ReportsPage } from "./ReportsPage";
export { default as GovernancePage } from "./GovernancePage";
export { default as SettingsPage } from "./SettingsPage";
